//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDAKDv2Entities : DbContext
    {
        public BDAKDv2Entities()
            : base("name=BDAKDv2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Usp_Grafica_EctomorgiaxJugador_Result> Usp_Grafica_EctomorgiaxJugador()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Grafica_EctomorgiaxJugador_Result>("Usp_Grafica_EctomorgiaxJugador");
        }
    
        public virtual ObjectResult<Usp_Grafica_EndomorfiaxJugador_Result> Usp_Grafica_EndomorfiaxJugador()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Grafica_EndomorfiaxJugador_Result>("Usp_Grafica_EndomorfiaxJugador");
        }
    
        public virtual ObjectResult<Usp_Grafica_MesomorfiaxJugador_Result> Usp_Grafica_MesomorfiaxJugador()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Grafica_MesomorfiaxJugador_Result>("Usp_Grafica_MesomorfiaxJugador");
        }
    
        public virtual ObjectResult<Usp_Grafica_ResultadosAll_Result> Usp_Grafica_ResultadosAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Grafica_ResultadosAll_Result>("Usp_Grafica_ResultadosAll");
        }
    }
}
