//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Jugador
    {
        public string codJugador { get; set; }
        public string aliasDeportivo { get; set; }
        public Nullable<int> numDorsal { get; set; }
        public string clubProcedencia { get; set; }
        public string lateralidad { get; set; }
        public string posicionPrincipal { get; set; }
        public string posicionAlternativa { get; set; }
        public Nullable<decimal> pesoInicial { get; set; }
        public Nullable<decimal> tallaInicial { get; set; }
        public string anio { get; set; }
        public string mes { get; set; }
        public string codUsuario { get; set; }
        public string codEquipo { get; set; }
        public Nullable<System.DateTime> jugadorFechaNac { get; set; }
    }
}
